version: '3'

services:
  service:
    build: service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DEPLOYMENT_ENVIRONMENT=docker-compose

  postgres:
    build: postgres
    restart: always
    environment:
      POSTGRES_DB: 'events'
      POSTGRES_USER: 'dbuser'
      POSTGRES_PASSWORD: 'dbpass'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
