spring:
  datasource:
    url: 'jdbc:h2:mem:events'
    driverClassName: 'org.h2.Driver'
    username: 'dbuser'
    password: ''
  jpa:
    hibernate:
      ddl-auto: 'create'
  h2:
    console:
      enabled: 'true'
      path: '/h2-console'

server:
  servlet:
    context-path: /api/v1
  tomcat:
    accept-count: 120
    mbeanregistry:
      enabled: true
    threads:
      max: 1200
